server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application.name: order-service

grpc:
  server:
    port: 9082
  client:
    product-service:
      address: 'discovery:///product-service'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

resilience4j:
  retry:
    instances:
      product-service:
        maxAttempts: 5
        waitDuration: 1s
        ignoreExceptions:
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
  circuitbreaker:
    instances:
      product-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: TIME_BASED
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 50s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"